Add required container port
Container port [is required](https://pkg.go.dev/k8s.io/api/core/v1#ContainerPort) and without I got the error message
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].ports[0]): missing required field "containerPort" in io.k8s.api.core.v1.ContainerPort
```